// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CheckCircleOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/Users/dokiyolo/Develop/VS Code Projects/AntDesignProDemo/secondapp/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, ProfileOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined };
